### ISSUE TITLE
关于下载方面的问题

### ISSUE THREAD

**Issue by wesleyx2** [tonquer/picacg-windows#41]
最近两个版本 下载的时候只能下载一个章节左右 然后就卡住显示出错了

log记录如下
2021-08-04 16:53:40,426 - log.py[line:54] - WARNING: task: <class 'src.server.req.GetComments'>, error
2021-08-04 16:53:40,427 - log.py[line:71] - ERROR: 'str' object has no attribute 'text'
Traceback (most recent call last):
  File "src\server\server.py", line 124, in _Send
  File "src\server\user_handler.py", line 256, in __call__
AttributeError: 'str' object has no attribute 'text'
2021-08-04 17:01:24,443 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:24,559 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:24,661 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:24,668 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:24,669 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:24,770 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:24,782 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:24,783 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:24,881 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:24,889 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:24,890 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,001 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,011 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,011 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,131 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,145 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,146 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,274 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,284 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,285 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,395 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,401 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,401 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,819 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,850 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:25,851 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:26,337 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement
2021-08-04 17:01:54,036 - log.py[line:54] - WARNING: near "sChannel『直播零距离』": syntax error Unable to execute statement

**Comment by tonquer** [comment]
应该是漫画名出现特殊字符的问题
把漫画名或者漫画id发一下，我试试

**Comment by wesleyx2** [comment]
漫画名就是 Solmi'sChannel『直播零距离』
不过之前感觉其他漫画也会出现错误 不知道是不是因为下载了这个后导致系统崩溃的问题
回头我再测试一下其他漫画 如果还会出错再提交一次log给大佬看看吧

**Comment by wesleyx2** [comment]
测试了好几部没发现问题 看来是我下载这部导致系统崩溃所以都失败的原因了吧

**Comment by tonquer** [comment]
v1.2.2已修复
