### ISSUE TITLE
UI文字渲染异常（错位、锯齿）

### ISSUE THREAD

**Issue by rihalvnium76** [tonquer/picacg-windows#93]
### 操作系统（如MacOS 10.15）
Win10 LTSC 2019 x64
bika_v1.2.8_windows_x64

### 问题描述（简要描述发生的问题）
从上一版本升级到该版本，并尝试过删除旧版残留的配置文件

#88 waifu2x文字被挤压无法正常显示，新版本依旧有（建议侧边栏各分栏可以用户自动调节宽度、高度）

窗口非最大化情况下：
![image](https://user-images.githubusercontent.com/57667144/142859920-73388c93-dfdf-4042-b91f-7f81ac2f7bb1.png)

窗口最大化情况下：
去噪等级的值被盖住了：
![image](https://user-images.githubusercontent.com/57667144/142860024-8860d6d4-296c-4a10-b968-2e705d6c5b53.png)
编辑状态下文字被压缩无法正常显示，且UI渲染异常：
![image](https://user-images.githubusercontent.com/57667144/142860191-c659726f-684b-4f6d-9558-51df7d0acd3b.png)

此外，新版本的Loading图，本子图片序号和图片本身显示模糊，锯齿明显
上一版本并没有这个问题
![image](https://user-images.githubusercontent.com/57667144/142860312-f81ff2a0-1f21-491b-8d5f-4101081ebc76.png)
![image](https://user-images.githubusercontent.com/57667144/142860635-d6895f5d-d40d-4e0d-932d-ab1c61be69fb.png)

### 日志提交（问题截图或者日志，日志在logs目录）
程序目录下logs目录没了

```
QLayout: Attempting to add QLayout "" to QWidget "LineEditHelp", which already has a layout
[0 NVIDIA GeForce GTX 1060]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1060]  bugsbn1=0  bugbilz=112  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1060]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1060]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) UHD Graphics 630]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) UHD Graphics 630]  bugsbn1=0  bugbilz=103  bugcopc=0  bugihfa=0
[1 Intel(R) UHD Graphics 630]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) UHD Graphics 630]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
QLayout: Attempting to add QLayout "" to LoginWidget "tab", which already has a layout
Exception in thread Thread-20:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "server\sql_server.py", line 72, in _Run
sqlite3.OperationalError: unable to open database file

UpdateLayeredWindowIndirect failed for ptDst=(241, 173), size=(1440x810), dirty=(1440x858 0, -18) (参数错误。)


2021-11-22 20:21:48,456 - server.py[line:187] - WARNING: https://picaapi.picacomic.com/collections ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='picaapi.picacomic.com', port=443): Read timed out. (read timeout=5)"))
QPropertyAnimation::updateState (): Changing state of an animation without target
2021-11-22 20:21:57,869 - server.py[line:270] - WARNING: https://storage.wikawika.xyz/static/tobeimg/7A71jL_KMdST8u8zZXHbNgWjuMCu9QZQx6gQ06jzSIM/fill/300/400/sm/0/aHR0cHM6Ly9zdG9yYWdlMS5waWNhY29taWMuY29tL3N0YXRpYy82ZWFhNjcyNy1mOTJjLTQ4YjQtOGFkMy1hZDA5MTI3YzM0MDguanBn.jpg ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='storage.wikawika.xyz', port=443): Read timed out. (read timeout=5)"))
2021-11-22 20:22:03,829 - user_handler.py[line:238] - ERROR: HTTPSConnectionPool(host='img.tipatipa.xyz', port=443): Read timed out.
Traceback (most recent call last):
  File "urllib3\response.py", line 436, in _error_catcher
  File "urllib3\response.py", line 518, in read
  File "http\client.py", line 461, in read
  File "http\client.py", line 505, in readinto
  File "socket.py", line 589, in readinto
  File "ssl.py", line 1071, in recv_into
  File "ssl.py", line 929, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\models.py", line 758, in generate
  File "urllib3\response.py", line 575, in stream
  File "urllib3\response.py", line 540, in read
  File "contextlib.py", line 130, in __exit__
  File "urllib3\response.py", line 441, in _error_catcher
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='img.tipatipa.xyz', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server\user_handler.py", line 220, in __call__
  File "requests\models.py", line 765, in generate
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='img.tipatipa.xyz', port=443): Read timed out.
QPropertyAnimation::updateState (): Changing state of an animation without target
QPropertyAnimation::updateState (): Changing state of an animation without target

```

**Comment by rihalvnium76** [comment]
（另外个人觉得1.2.7（上一版本）的UI比新版的UI顺眼）

**Comment by tonquer** [comment]
后续把这个做成超过大小上下滚动。
这个版本做了自适应dpi，控件会根据系统的缩放比例放大，可能是导致模糊了

**Comment by tonquer** [comment]
> （另外个人觉得1.2.7（上一版本）的UI比新版的UI顺眼）

这个版本用的material主题，不过白色下和它演示的效果相差有点大😞

**Comment by tonquer** [comment]
你这个日志报错了，你似乎没有解压压缩包里的data目录。将无法使用本地搜索

**Comment by rihalvnium76** [comment]
> 你这个日志报错了，你似乎没有解压压缩包里的data目录。将无法使用本地搜索

似乎你的发布的压缩包本身就是缺文件的

**Comment by tonquer** [comment]
已修改，如果你屏幕比较小，建议在设置里设置缩放为100%
